name: Cleanup Failed Dependency Updates

on:
  workflow_run:
    workflows: ["Safe Daily Dependency Update"]
    types: [completed]
    branches: [main]

jobs:
  cleanup-failed-runs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up failed PR branches
        uses: actions/github-script@v7
        with:
          script: |
            const { data: branches } = await github.rest.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const failedBranches = branches.filter(branch => 
              branch.name.startsWith('dependency-update-') && 
              branch.name !== 'dependency-update'
            );
            
            console.log(`Found ${failedBranches.length} dependency update branches to clean up`);
            
            for (const branch of failedBranches) {
              try {
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `heads/${branch.name}`
                });
                console.log(`✅ Deleted branch: ${branch.name}`);
              } catch (error) {
                console.log(`⚠️ Failed to delete branch ${branch.name}: ${error.message}`);
              }
            }

  notify-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
      - name: Create issue for failed workflow
        uses: actions/github-script@v7
        with:
          script: |
            const workflowRun = context.payload.workflow_run;
            
            const issueBody = `## 🚨 Dependency Update Workflow Failed
            
            The daily dependency update workflow failed and needs attention.
            
            ### 📋 Details
            - **Workflow Run:** [${workflowRun.id}](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${workflowRun.id})
            - **Failed At:** ${workflowRun.updated_at}
            - **Triggered By:** ${workflowRun.event}
            
            ### 🔍 Next Steps
            1. Check the [workflow logs](${workflowRun.html_url})
            2. Identify the root cause of the failure
            3. Fix any issues in the workflow or dependencies
            4. Re-run the workflow manually if needed
            
            ### 📊 Common Issues
            - Dependency conflicts
            - Build failures
            - Test failures
            - Network issues
            - Permission problems
            
            ---
            
            **Auto-generated by cleanup workflow**`;
            
            try {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `🚨 Dependency Update Workflow Failed - ${new Date().toISOString().split('T')[0]}`,
                body: issueBody,
                labels: ['bug', 'dependencies', 'workflow-failure'],
                assignees: [context.repo.owner]
              });
              console.log('✅ Created issue for failed workflow');
            } catch (error) {
              console.log(`⚠️ Failed to create issue: ${error.message}`);
            } 